-- Criação da tabela de cards para o FirstApp

CREATE TABLE IF NOT EXISTS public.cards (
    id bigint generated by default as identity primary key,
    title text not null,
    content text,
    image_path text,
    locked_by uuid references auth.users(id),
    locked_at timestamp with time zone,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Configuração do RLS (Row Level Security) para permitir que acessos anônimos façam CRUD (apenas para exemplo, não recomendado para produção)
-- Configuração do RLS (Row Level Security)
ALTER TABLE public.cards ENABLE ROW LEVEL SECURITY;

-- Permite a qualquer um ler os cards
CREATE POLICY "Enable read access for all users" ON public.cards
    FOR SELECT
    USING (true);

-- Permite apenas usuários autenticados criar, atualizar ou deletar
CREATE POLICY "Enable insert for authenticated users only" ON public.cards
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users only" ON public.cards
    FOR UPDATE
    TO authenticated
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Enable delete for authenticated users only" ON public.cards
    FOR DELETE
    TO authenticated
    USING (true);

-- Configuração do RLS para o Storage
-- Permite que usuários autenticados façam upload de arquivos para o bucket 'firstappfiles'
CREATE POLICY "Allow authenticated uploads"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'firstappfiles');
