name = "firstapp"
compatibility_date = "2023-10-30"
main = "worker.js"

[assets]
directory = "public"

# ...
[observability.logs]
enabled = true
invocation_logs = true
persist = true
# ...
# ...
[vars]
SUPABASE_PUBLISHABLE_KEY = "sb_publishable_ABMBNom80X3Bwf9wzY7doQ_qgPsqV4W"
SUPABASE_URL = "https://fhmcmprjyxncbpeirmnu.supabase.co"
# ...


