name = "firstapp"
compatibility_date = "2023-10-30"
main = "worker.js"

[assets]
directory = "public"

# ...
[observability.logs]
enabled = true
invocation_logs = true
persist = true
# ...
# ...
[vars]
APPWRITE_ENDPOINT = "https://sfo.cloud.appwrite.io/v1"
APPWRITE_PROJECT_ID = "6ab7319800354a4656bd"
APPWRITE_DATABASE_ID = "firstapp" # A definir
APPWRITE_COLLECTION_ID = "cards" # A definir
APPWRITE_BUCKET_ID = "firstappfiles" # A definir
# ...


